module.exports = {
  CLIENT_MESSAGE: 'CLIENT_MESSAGE',
  SERVER_MESSAGE: 'SERVER_MESSAGE',
  CLIENT_USERNAME: 'CLIENT_USERNAME',
  EMIT_USERNAMES: 'EMIT_USERNAMES',
  EMIT_NEW_USER: 'EMIT_NEW_USER',
  EMIT_USER_LEFT: 'EMIT_USER_LEFT'
}
